from .models import PromptTemplate

# Metadata is adapted from the public awesome-gpt-image-2 and GPT-Image2-Skill galleries.
# Full case prompts stay in the external galleries so this application does not mirror them.
PROMPT_TEMPLATES = (
    PromptTemplate(
        "game-ui-gameplay-hud",
        "游戏实机 HUD",
        "game_ui",
        ("Game UI", "HUD", "UI"),
        ("Gaming", "Story"),
        "第三人称、第一人称或等距游戏的单一实机游玩 HUD",
        (
            "先写平台、目标画布、镜头语境和安全区，再按左上/右上/左下/右下/中心逐区定义 HUD；边框和装饰也必须留在安全区内。",
            "给出血量、护盾、体力、弹药、资源、任务、地图、准星等实际状态和精确数字；背景只保留能证明实机语境的可玩场景。",
            "规定 UI 层级、对齐、间距、图标尺寸、字体层级、对比度和不遮挡规则，明确这是游戏截图而不是海报。",
        ),
        (
            "避免把 HUD 元素漂浮在无逻辑的宣传构图上。",
            "避免额外 Logo、随机任务文字、乱码和越过安全区的控件。",
            "避免贴着画布边缘的全幅装饰框、角标和无功能科技线。",
        ),
        (),
        case_refs=("skill:15", "skill:18", "skill:19"),
        gallery_categories=("gaming", "screen-photography"),
        required_fields=(
            "platform",
            "canvas",
            "screen_type",
            "hud_zones",
            "safe_area",
            "exact_text",
            "ui_states",
        ),
        hard_checks=(
            "输出为单一实机游玩状态而非海报",
            "HUD 分区完整且不遮挡主要可玩信息",
            "关键数值和文字逐字可读",
            "没有越过安全区的全幅装饰边框",
        ),
    ),
    PromptTemplate(
        "game-ui-menu-inventory",
        "游戏菜单 / 背包界面",
        "game_ui",
        ("Game UI", "UI", "Infographic"),
        ("Gaming", "Tech"),
        "暂停菜单、角色状态、背包、装备或技能页面的单一界面状态",
        (
            "明确屏幕用途、导航层级、选中项、分页、物品格数量和信息密度；给出一个可执行的静态状态。",
            "把角色预览、物品缩略图、属性数值、稀有度、容量和操作提示分成固定区域，统一卡片、图标和网格间距。",
            "所有标题、属性和按钮文案使用短的原创游戏术语；优先高对比和可扫描性，不用装饰性长文案。",
        ),
        (
            "避免同时展示背包、地图、商店和战斗 HUD 多个页面。",
            "避免卡片数量、选中状态和操作提示互相矛盾。",
        ),
        (),
        case_refs=("skill:17", "skill:20"),
        required_fields=(
            "platform",
            "screen_type",
            "navigation",
            "selected_state",
            "grid_and_slots",
            "exact_text",
        ),
        hard_checks=(
            "页面类型和选中状态明确",
            "物品格与属性区域数量一致",
            "导航、标题和操作提示可读",
        ),
    ),
    PromptTemplate(
        "game-ui-map-quest",
        "游戏地图 / 任务界面",
        "game_ui",
        ("Game UI", "HUD", "Infographic"),
        ("Gaming", "Tech"),
        "世界地图、区域地图、任务日志、指南针和路线规划界面",
        (
            "先确定地图尺度、朝向、玩家位置、任务目标、路线、图例和缩放层级，固定每类标记的视觉编码。",
            "把地图内容、任务面板、指南针/坐标和操作提示分区，标签只用确认过的短词，保证地标与标记的相对位置清楚。",
            "地图要有游戏世界的可玩信息和空间关系，不做旅游海报；使用原创地点名和图例。",
        ),
        (
            "避免随机地名、重叠标记、没有方向的地图和过密长文本。",
            "避免把任务日志与战斗 HUD 叠成无层级的界面。",
        ),
        (),
        case_refs=("skill:19", "skill:21"),
        required_fields=(
            "platform",
            "screen_type",
            "map_scale",
            "orientation",
            "markers_and_legend",
            "quest_text",
        ),
        hard_checks=(
            "玩家、目标和路线关系清楚",
            "图例与标记编码一致",
            "任务文字短且可读",
        ),
    ),
    PromptTemplate(
        "game-ui-production-asset",
        "游戏 UI 开发组件",
        "game_ui",
        ("Game UI", "HUD", "UI"),
        ("Gaming", "Tech"),
        "把完整 HUD 或菜单作为参考，重建可直接用于引擎的单个原子 UI 资源",
        (
            "先把参考界面整理为“模块 → 原子资源”组件树，并让用户明确选择本次要制作的一个原子资源；未选定前只澄清，不输出生图提示词。",
            "参考图只负责结构、比例、材质和配色，不从扁平截图抠取或复制混有场景背景的像素；每次只重建一个空面板、边框、图标、装饰、轨道、填充或状态资源。",
            "面板和边框移除文字、数值、图标及内容层，说明九宫格拉伸需求；图标只保留单一语义；状态条把轨道、填充和开关状态拆开。",
            "最终素材使用透明背景，完整轮廓四周保留安全留白；文字、动态数值、颜色参数和布局坐标写入 production_spec，不烘焙到图片。",
        ),
        (
            "避免输出整屏 UI、多个面板、组件展示板、Sprite Sheet 或任何由 AI 排版的图集。",
            "避免把游戏场景、透明棋盘格、参考图文字、动态数值或相邻组件带入素材。",
            "避免声称像素级复刻、无损拆层或自动抠图；被背景污染的内容必须重新绘制。",
        ),
        (),
        required_fields=(
            "platform",
            "component_tree",
            "asset_module",
            "atomic_asset",
            "asset_type",
            "runtime_content",
            "transparent_output",
            "nine_slice",
        ),
        hard_checks=(
            "最终图片只包含一个选定的原子 UI 资源",
            "素材外部为真实透明像素且轮廓没有背景污染",
            "图片不包含文字、动态数值、相邻组件或图集排版",
            "空面板和边框保留可九宫格拉伸的干净区域",
        ),
    ),
    PromptTemplate(
        "game-ui-icon-sheet",
        "游戏图标资产集",
        "game_ui",
        ("Game UI", "Icon Sheet", "Illustration"),
        ("Gaming", "Creative"),
        "技能、装备、物品、状态效果和地图标记的统一图标集",
        (
            "固定网格行列、图标总数、每格职责、显示尺寸、背景和透明/纯色输出规则；每个图标只表达一个可读语义。",
            "统一轮廓、视角、描边/材质、光源、稀有度色板和留白；用编号或极短标签对应图标职责。",
            "图标要在实际 HUD 尺寸下仍能辨认，禁止把图标集做成角色海报或无用途的装饰拼贴。",
        ),
        (
            "避免图标数量不符、语义重复、视角和材质混乱。",
            "避免随机字母、品牌 Logo、复杂背景和无法缩小的细节。",
        ),
        (),
        case_refs=("skill:20", "awesome:370"),
        required_fields=(
            "platform",
            "grid",
            "icon_count",
            "icon_roles",
            "display_size",
            "palette",
        ),
        hard_checks=(
            "网格和图标数量正确",
            "每个图标语义独立且风格统一",
            "缩小后轮廓仍清晰",
        ),
    ),
    PromptTemplate(
        "game-art-key-visual",
        "游戏 Key Art / 主视觉",
        "game_art",
        ("Game Art", "Key Art", "Concept Art"),
        ("Gaming", "Story"),
        "游戏宣传主视觉、章节封面或核心事件的单张 Key Art",
        (
            "明确游戏世界、阵营、角色身份、正在发生的事件和交付用途；只保留一个主叙事瞬间和一个视觉中心。",
            "写清前景/中景/背景、镜头高度、焦段感、动作方向、尺度参照、材质和光线，让画面服务可玩世界。",
            "原创标题或短标签若非必要就不加入；禁止真实游戏 Logo/IP，保留可供美术继续开发的轮廓和色板信息。",
        ),
        (
            "避免把 Key Art 变成角色表、九宫格或 UI 截图。",
            "避免堆叠多个高潮动作、无尺度的背景和无关文字。",
        ),
        (),
        case_refs=("awesome:473", "awesome:395", "awesome:394"),
        gallery_categories=("gaming", "cinematic-film-references"),
        required_fields=(
            "deliverable_stage",
            "world_and_faction",
            "identity_anchors",
            "camera_and_action",
            "composition",
            "palette_and_lighting",
        ),
        hard_checks=(
            "只有一个明确叙事瞬间和视觉中心",
            "角色身份与世界尺度可信",
            "无真实 IP、Logo 和额外文字",
        ),
    ),
    PromptTemplate(
        "game-art-character-sheet",
        "游戏角色设定表",
        "game_art",
        ("Game Art", "Character", "Concept Art"),
        ("Gaming", "Story"),
        "角色三视图、表情、服装装备和比例参考设定表",
        (
            "固定页面网格和视图职责：正面/侧面/背面、动作或表情、服装层级、装备拆解和色板。",
            "先锁身份锚点（脸型、发型、体型、服装剪影、阵营符号和主色），所有面板复用同一角色和同一装备状态。",
            "白发、疤痕、单侧护甲和机械臂等非对称锚点必须写明角色左右，并映射到正面、侧面、背面和头像中的观看方向。",
            "标注只写短的部件名或材质名；让比例、关节、鞋底、武器握持和功能细节可供制作参考。",
        ),
        (
            "避免面板间换脸、换发型、换装备、比例漂移或随机角色。",
            "避免把角色设定表做成只有一张大头像的海报。",
        ),
        (),
        case_refs=("skill:31", "skill:32", "awesome:439"),
        gallery_categories=("character-design", "gaming"),
        required_fields=(
            "panel_count",
            "panel_roles",
            "identity_anchors",
            "directional_identity_map",
            "views_and_expressions",
            "costume_and_equipment",
            "palette",
        ),
        hard_checks=(
            "视图和面板数量正确",
            "所有面板保持同一身份、服装、装备及非对称特征方向",
            "部件标签短且可读",
        ),
    ),
    PromptTemplate(
        "game-art-environment",
        "游戏环境概念图",
        "game_art",
        ("Game Art", "Environment", "Concept Art"),
        ("Gaming", "Story"),
        "关卡环境、城镇、遗迹、战场和可探索空间的环境概念",
        (
            "说明关卡功能、玩家动线、关键地标、入口/出口、可交互物和尺度参照，而不是只写‘宏大风景’。",
            "明确镜头高度、视线引导、前中后景、材质分层、天气和主光方向；关键区域要能支持导航与玩法。",
            "保留适度的制作信息（模块化结构、重复材质、破损逻辑和色板），让环境概念能转成关卡语言。",
        ),
        (
            "避免没有玩法线索的壁纸式风景。",
            "避免建筑结构、尺度、光源和动线互相矛盾。",
        ),
        (),
        case_refs=("awesome:473", "awesome:448", "awesome:394"),
        required_fields=(
            "environment_function",
            "player_route",
            "landmarks",
            "scale_reference",
            "camera",
            "materials",
            "lighting",
        ),
        hard_checks=(
            "关键地标和玩家动线可读",
            "尺度、结构和光线一致",
            "环境细节服务玩法而非纯装饰",
        ),
    ),
    PromptTemplate(
        "game-art-prop-weapon",
        "游戏武器 / 道具设计",
        "game_art",
        ("Game Art", "Props", "Concept Art"),
        ("Gaming", "Tech"),
        "武器、装备、载具部件和关键道具的制作设计页",
        (
            "先写功能、使用者、尺寸级别和关键轮廓，再安排正交视图、握持/使用状态、材质拆分和局部放大。",
            "用结构、连接、磨损、能源/机械逻辑和尺度参照证明它能在游戏世界里工作；需要时加入简短部件标签。",
            "固定面板数量和职责，统一视角、光线、色板与原创阵营符号，避免只画一个漂亮但不可制作的物件。",
        ),
        (
            "避免功能、比例、连接关系和视图相互矛盾。",
            "避免随机技术文字、真实品牌和无关武器堆叠。",
        ),
        (),
        case_refs=("skill:112", "skill:113", "skill:114", "awesome:370"),
        gallery_categories=("technical-illustration", "gaming"),
        required_fields=(
            "prop_function",
            "user_and_scale",
            "views",
            "material_breakdown",
            "mechanical_details",
            "callouts",
        ),
        hard_checks=(
            "视图和部件关系一致",
            "尺度、功能和材质可判断",
            "标签只包含必要短文本",
        ),
    ),
    PromptTemplate(
        "game-art-worldbuilding-board",
        "游戏世界观设定板",
        "game_art",
        ("Game Art", "Worldbuilding", "Concept Art"),
        ("Gaming", "Creative"),
        "3×3 或指定网格的阵营、地点、角色、道具和事件世界观板",
        (
            "先锁定网格数量和每格职责；所有格子共享游戏名、时代、阵营、色板、材质、符号和光线规则。",
            "为每格指定一个互补的制作问题（角色、敌人、环境、道具、事件、地图等），而不是生成九张相互无关的插图。",
            "页眉、短标题和标注只服务检索；确保跨面板身份、服装、装备和世界规则一致。",
        ),
        (
            "避免面板数量漂移、重复内容、无关风格和随机长文案。",
            "避免把外部游戏案例中的角色、Logo 或名称直接带入原创项目。",
        ),
        (),
        case_refs=("skill:22", "awesome:473"),
        gallery_categories=("gaming", "cinematic-and-animation"),
        required_fields=(
            "panel_count",
            "panel_roles",
            "shared_identity_anchors",
            "shared_palette",
            "shared_materials",
            "labels",
        ),
        hard_checks=(
            "网格数量和每格职责正确",
            "所有面板共享同一世界规则",
            "无额外面板、IP 和无关文字",
        ),
    ),
    PromptTemplate(
        "game-art-action-breakdown",
        "游戏动作分解板",
        "game_art",
        ("Game Art", "Action Board", "Character"),
        ("Gaming", "Story"),
        "攻击、移动、受击、施法和交互动作的连续分解参考板",
        (
            "固定帧数或网格、阅读顺序和每帧职责；同一角色、服装、武器、镜头轴线和背景锚点贯穿全部帧。",
            "写清起势、发力、接触、峰值、回收和残影/特效的动作节拍，用轮廓、重心、运动线和接触点服务动画制作。",
            "必要标签保持短且准确，避免把动作分解变成多张独立海报或不同角色的姿势合集。",
        ),
        (
            "避免帧数不一致、动作顺序混乱、角色身份漂移和镜头轴线跳变。",
            "避免无关装饰、长段说明和真实游戏动作复刻。",
        ),
        (),
        case_refs=("awesome:347", "skill:32"),
        gallery_categories=("cinematic-and-animation", "gaming"),
        required_fields=(
            "frame_count",
            "frame_roles",
            "identity_anchors",
            "action_beats",
            "camera_axis",
            "effects",
        ),
        hard_checks=(
            "帧数、顺序和动作节拍正确",
            "角色、服装、武器和镜头轴线一致",
            "每帧都能判断动作阶段",
        ),
    ),
    PromptTemplate(
        "ui-screenshot-system",
        "UI 截图系统",
        "ui",
        ("UI",),
        ("Tech", "Social"),
        "App 截图、仪表盘、社媒截图和直播界面",
        ("锁定平台、比例、层级和画面文字。", "明确状态栏、Tab、操作区和评论层。"),
        ("避免平台描述过泛。", "约束文字可读性和平台特征。"),
        (17, 2, 4),
        case_refs=("skill:102", "skill:103", "skill:104", "skill:106"),
    ),
    PromptTemplate(
        "infographic-engine",
        "信息图引擎",
        "infographic",
        ("Infographic", "Charts"),
        ("Education", "Tech"),
        "解释图、技术图解、时间线和知识卡片",
        ("定义 3-5 个模块、信息流、层级和短标签。", "用色块、箭头、图标和留白控制复杂度。"),
        ("避免长段正文。", "先限制模块数量，再补视觉细节。"),
        (334, 1, 8),
        case_refs=("skill:68", "skill:69", "skill:74"),
    ),
    PromptTemplate(
        "scientific-scale-diagram",
        "科学尺度缩放图",
        "infographic",
        ("Infographic", "Charts", "Realistic"),
        ("Education", "Tech"),
        "从微观到宏观展示尺度变化的科普主题",
        ("使用 6-8 个尺度框和短标签。", "展示单位、倍率和不同尺度的细节。"),
        ("避免所有尺度框相同。", "避免通用放大镜式布局。"),
        (341,),
        case_refs=("skill:122", "skill:126"),
    ),
    PromptTemplate(
        "research-paper-figure",
        "科研论文方法图",
        "infographic",
        ("Research Figure", "Charts", "Infographic"),
        ("Research", "Education", "Tech"),
        "论文方法总览、系统架构、实验流程、安全分析和多面板学术图",
        (
            "先写横竖画幅、论文风格和面板结构，再定义列、区域、节点、模块、时间线或热图等图形语法。",
            "逐字给出模块名、轴、单位、图例和关键数值；用箭头方向、线型、颜色和粗细说明关系语义。",
            "要求白底、对齐、留白和大号可读标签；生成结果只作工作流草图或视觉目标，不声称数据真实。",
        ),
        (
            "避免用装饰插画替代可验证的流程和关系。",
            "避免臆造研究结论、指标、样本量和论文数据。",
        ),
        (),
        case_refs=("skill:75", "skill:79", "skill:81", "skill:95"),
        required_fields=(
            "figure_type",
            "panel_structure",
            "exact_labels",
            "relationships",
            "legend_and_units",
            "visual_encoding",
        ),
        hard_checks=(
            "面板数量和阅读顺序正确",
            "节点、箭头和关系语义一致",
            "标签、图例和单位清晰可读",
            "不包含未经用户提供的研究数据或结论",
        ),
    ),
    PromptTemplate(
        "data-visualization-system",
        "数据可视化系统",
        "infographic",
        ("Data Visualization", "Charts"),
        ("Research", "Education", "Tech"),
        "小多图、网络图、弦图、树图、地图、热图及其他数据驱动图表",
        (
            "先声明图表家族和画布结构，再给出数据维度、面板、轴、单位、图例和所有必须显示的标签。",
            "明确颜色、位置、面积、线条或带宽分别编码什么；重复面板共享尺度、基线、间距和排序。",
            "数据不完整时先澄清，不得用看似精确的随机数填充。",
        ),
        (
            "避免选择与数据关系不匹配的图表家族。",
            "避免装饰图标、3D 效果和小字破坏比较准确性。",
        ),
        (),
        case_refs=("skill:107", "skill:108", "skill:109", "skill:111"),
        required_fields=(
            "chart_family",
            "data_dimensions",
            "axes_and_units",
            "legend",
            "visual_encoding",
            "exact_labels",
        ),
        hard_checks=(
            "图表家族与数据关系匹配",
            "轴、单位、图例和标签完整",
            "视觉编码前后一致",
            "重复面板使用相同尺度和对齐",
        ),
    ),
    PromptTemplate(
        "technical-exploded-cutaway",
        "技术爆炸 / 剖切图",
        "infographic",
        ("Technical Illustration", "Infographic", "Props"),
        ("Tech", "Education"),
        "机械、产品、装备、建筑构件或装置的爆炸图、剖切图和部件说明板",
        (
            "确定爆炸、剖切或正投影视图，按装配顺序列出部件、相对位置、尺度、材料和功能。",
            "使用编号、短标签、引线、局部放大和材料图例；所有部件沿一致轴线且能还原装配关系。",
            "技术风格服务结构说明，不用炫光、烟雾或无功能细节遮挡关键连接。",
        ),
        (
            "避免部件数量、编号和装配顺序互相矛盾。",
            "避免把概念海报误作可读技术图。",
        ),
        (),
        case_refs=("skill:112", "skill:113", "skill:114", "skill:116"),
        required_fields=(
            "view_type",
            "component_order",
            "materials",
            "scale_reference",
            "callouts",
            "assembly_axis",
        ),
        hard_checks=(
            "部件数量、编号和标签一致",
            "相对位置与装配顺序可判断",
            "引线不交叉遮挡关键结构",
            "材料、尺度和功能表达清楚",
        ),
    ),
    PromptTemplate(
        "scientific-education-board",
        "科学教育图板",
        "infographic",
        ("Scientific", "Infographic", "Illustration"),
        ("Education", "Research", "Healthcare"),
        "解剖、地质、天文、化学、生物和课堂知识图板",
        (
            "准确命名主题、观察视图和受众，定义标题、主体图、剖面/对照、标注、图例和尺度说明等固定版区。",
            "使用课堂挂图或科学图版的清楚层级、细引线和克制色板；逐字提供必须正确的术语。",
            "区分已知事实、示意比例和艺术化部分，不生成未经用户确认的医学诊断或危险操作。",
        ),
        (
            "避免夸张写实、血腥细节和伪科学装饰。",
            "避免把长段百科正文压缩成不可读小字。",
        ),
        (),
        case_refs=("skill:122", "skill:123", "skill:126", "skill:128"),
        required_fields=(
            "scientific_subject",
            "audience",
            "views",
            "fixed_regions",
            "exact_labels",
            "scale_and_legend",
        ),
        hard_checks=(
            "主题、视图和版区完整",
            "科学术语和标签逐字可读",
            "图例、尺度和引线对应正确",
            "不包含误导性诊断、数据或伪科学结论",
        ),
    ),
    PromptTemplate(
        "poster-layout-system",
        "海报排版系统",
        "poster",
        ("Poster",),
        ("Commerce", "Social"),
        "活动、电影、封面和社媒传播海报",
        ("锁定主体、标题、版式、配色和比例。", "突出标题层级和主视觉。"),
        ("避免拼贴展示板。", "约束多余文字和装饰符号。"),
        (345, 5, 10),
        case_refs=("skill:33", "skill:41", "skill:45"),
    ),
    PromptTemplate(
        "sports-campaign-poster",
        "运动商业 Campaign",
        "poster",
        ("Poster", "Realistic"),
        ("Commerce", "Fashion"),
        "运动品牌 Campaign、运动员和运动产品视觉",
        ("定义运动项目、姿态、核心道具、标题和品牌色。", "使用强光影、干净构图和可读数据层。"),
        ("避免错误运动器材和杂乱拼贴。", "让运动员和核心道具占据主导。"),
        (350, 3),
        gallery_categories=("typography-and-posters", "events-and-experience"),
    ),
    PromptTemplate(
        "conceptual-typography-poster",
        "概念字体海报",
        "poster",
        ("Poster",),
        ("Creative", "Social"),
        "标题文字成为主视觉结构的海报",
        ("让字体成为画面主角并保证拼写准确。", "人物、物体或风景服务标题含义。"),
        ("避免默认字效、无关图标和标题错字。", "控制配色数量。"),
        (355,),
    ),
    PromptTemplate(
        "ink-double-exposure-poster",
        "水墨双重曝光海报",
        "poster",
        ("Poster", "Illustration", "Classical"),
        ("Story", "History"),
        "诗意人像海报、水墨氛围和文化主题视觉",
        ("融合人像剪影、水墨质感、氛围和留白。", "保持构图克制、高级、可读。"),
        ("避免廉价奇幻拼贴和景物堆叠。", "非必要时减少文字。"),
        (359,),
        gallery_categories=("ink-and-chinese", "typography-and-posters"),
    ),
    PromptTemplate(
        "nature-science-poster",
        "自然科普海报",
        "poster",
        ("Poster", "Infographic"),
        ("Education",),
        "自然主题的干净科普海报",
        ("使用清晰主体、少量文案、柔和阴影和留白。", "让科普标签短而清楚。"),
        ("避免广告感过重。", "避免密集百科正文。"),
        (339,),
    ),
    PromptTemplate(
        "product-commerce-visual",
        "商品商业视觉",
        "product",
        ("Product", "Realistic"),
        ("Commerce", "Food"),
        "商品主图、包装视觉、详情页和卖点排版",
        ("定义商品、卖点、材质、场景、光线和版块。", "区分主商品、卖点标签和辅助道具。"),
        ("避免无关道具削弱商品识别。", "约束包装文字和卖点表达。"),
        (373, 358),
        case_refs=("skill:56", "skill:57", "skill:59"),
    ),
    PromptTemplate(
        "structured-product-food-render",
        "结构化商品 / 食品渲染",
        "product",
        ("Product", "Photography", "Realistic"),
        ("Commerce", "Food"),
        "复杂商品英雄图、食品动态摄影及需要精确控制材料和光线的商业画面",
        (
            "使用干净的 JSON/config 分区描述全局画幅、环境、核心商品、材料、光线、动态细节和输出目标。",
            "产品几何、标签和品牌属于不变量；材料、光线、色板和粒子/液体运动分别控制。",
            "数组只列可见元素，值使用具体视觉事实；禁止用大量 8K、premium 等空质量词代替内容。",
        ),
        (
            "避免结构化格式里出现实现代码或互相冲突的设置。",
            "避免改变包装几何、标签文字和食物物理关系。",
        ),
        (),
        case_refs=("skill:57", "skill:58"),
        required_fields=(
            "aspect_ratio",
            "environment",
            "primary_subject",
            "materials",
            "lighting",
            "motion_or_details",
            "output_mood",
        ),
        hard_checks=(
            "商品或食品主体几何正确",
            "材料、光线和色板彼此一致",
            "动态细节符合可信物理关系",
            "没有随机品牌、标签或促销文字",
        ),
    ),
    PromptTemplate(
        "personalized-beauty-report",
        "个性化美妆报告",
        "product",
        ("Product", "UI"),
        ("Commerce", "Fashion"),
        "美妆推荐、肤质报告、导购助手和商品卡片",
        ("使用诊断、推荐和商品卡片的报告层级。", "对齐商品图、标签和评分。"),
        ("避免医疗化结论和难读小字。", "保持推荐逻辑清楚。"),
        (353,),
        gallery_categories=("beauty-and-lifestyle",),
    ),
    PromptTemplate(
        "brand-identity-package",
        "品牌身份包",
        "brand",
        ("Brand",),
        ("Commerce",),
        "Logo 系统、品牌板、VI 套件和应用样机",
        ("定义品牌名、定位、配色、字体、Logo 用法和触点。", "要求视觉板中的应用统一对齐。"),
        ("避免无关 Logo 变体和混乱配色。", "保持品牌文字准确。"),
        (354,),
        case_refs=("skill:60", "skill:61", "skill:62"),
    ),
    PromptTemplate(
        "brand-touchpoint-board",
        "品牌触点视觉板",
        "brand",
        ("Brand", "Product"),
        ("Commerce", "Social"),
        "多触点 Campaign 展示和品牌落地预览",
        ("指定触点清单、统一视觉规则和样机排列。", "让所有面板共享配色和字体逻辑。"),
        ("避免混入无关 Campaign 风格。", "可读性下降时减少触点。"),
        (362,),
    ),
    PromptTemplate(
        "architecture-space",
        "建筑与空间",
        "architecture",
        ("Architecture",),
        ("Travel", "Commerce"),
        "室内、建筑表现、城市地图和空间规划",
        ("定义视角、尺度、材质、光线和空间功能。", "地图需指定地标、标签和相对位置。"),
        ("避免不合理透视。", "锁定地图标签语言和位置。"),
        (331, 11),
        case_refs=("skill:117", "skill:118", "skill:121"),
        gallery_categories=("architecture-and-interior", "isometric"),
    ),
    PromptTemplate(
        "realistic-photography",
        "写实摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Fashion", "Commerce"),
        "人像、街拍、商品摄影和电影感写实",
        ("指定机位、镜头、光源、质感、背景和动作。", "加入可信的小瑕疵增强纪实感。"),
        ("商业美妆之外避免过度磨皮。", "按需约束手部、文字和结构。"),
        (377,),
        case_refs=("skill:63", "skill:64", "skill:66"),
    ),
    PromptTemplate(
        "street-accident-moment",
        "街头意外瞬间摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Travel", "Social"),
        "街头抓拍、意外泼洒、手机纪实和快速动作",
        ("描述具体瞬间、机位高度、运动模糊和街景。", "加入避免摆拍和棚拍感的限制。"),
        ("避免画面过于干净。", "让事件看起来可信。"),
        (376,),
        case_refs=("skill:65", "skill:161", "skill:162"),
        gallery_categories=("photography",),
    ),
    PromptTemplate(
        "fashion-editorial-story",
        "时尚编辑摄影",
        "photo",
        ("Fashion Editorial", "Photography", "Cinematic"),
        ("Fashion", "Lifestyle", "Commerce"),
        "成年模特时装大片、杂志封面、造型故事和品牌编辑视觉",
        (
            "明确成年主体、服装廓形、面料、配饰、姿态和叙事情境，再选择一个主导机位、镜头感和光线方案。",
            "封面或跨页先定义标题和短文案层级；时装、环境和色板共同服务一个编辑主题。",
            "保持高端但真实的皮肤与面料细节，公共输出必须非露骨、非裸露且不仿冒真实品牌 Campaign。",
        ),
        (
            "避免用过度磨皮、塑料皮肤和无功能奢侈品堆砌表达高级感。",
            "避免年龄含混、身体比例失真和随机杂志文字。",
        ),
        (),
        case_refs=("skill:129", "skill:131", "skill:135"),
        required_fields=(
            "adult_subject",
            "wardrobe",
            "pose",
            "editorial_story",
            "camera",
            "lighting",
            "exact_text",
        ),
        hard_checks=(
            "主体明确为成年人且内容非露骨",
            "服装廓形、面料和配饰一致",
            "镜头、姿态和光线服务同一编辑主题",
            "没有随机品牌或杂志文字",
        ),
    ),
    PromptTemplate(
        "illustration-art-style",
        "插画与艺术风格",
        "illustration",
        ("Illustration",),
        ("Story", "Creative"),
        "动漫、水彩、水墨、装饰画和风格实验",
        ("定义构图、主体、配色、笔触材质、情绪和完成度。", "参考图任务写明保留特征。"),
        ("避免只写风格不写构图。", "使用参考图时锁定角色识别。"),
        (346, 6),
        case_refs=("skill:46", "skill:48", "skill:50", "skill:141"),
        gallery_categories=("illustration", "more-illustration-styles"),
    ),
    PromptTemplate(
        "anime-manga-production-board",
        "动漫 / 漫画制作板",
        "illustration",
        ("Anime", "Manga", "Character", "Illustration"),
        ("Story", "Creative"),
        "原创动漫角色、表情网格、漫画页、动作板和多角色制作设定",
        (
            "固定画布、格数、阅读顺序和每格职责；先写角色身份锚点，再写动作、表情、镜头和环境。",
            "明确线稿、赛璐璐、网点、速度线或动画制作语法，并在所有格重复脸、发型、服装和色板。",
            "借鉴媒介和制作特征但保持原创角色，不复制现有 IP、工作室角色、Logo 或对白。",
        ),
        (
            "避免跨格换脸、服装漂移、格数错误和阅读顺序混乱。",
            "避免仅靠工作室或作品名称替代可执行风格说明。",
        ),
        (),
        case_refs=("skill:1", "skill:5", "skill:10", "skill:12"),
        required_fields=(
            "board_type",
            "panel_count",
            "panel_roles",
            "identity_anchors",
            "line_and_shading",
            "consistency_rules",
        ),
        hard_checks=(
            "面板数量、顺序和职责正确",
            "角色身份、服装和比例跨格一致",
            "线稿、上色和色板统一",
            "没有现有 IP、Logo 或额外对白",
        ),
    ),
    PromptTemplate(
        "tattoo-design-system",
        "纹身设计系统",
        "illustration",
        ("Tattoo", "Illustration", "Fine Art"),
        ("Creative", "Fashion"),
        "黑灰、传统彩色、日式传统和黑暗超现实纹身设计或 flash 板",
        (
            "先指定身体部位、覆盖范围和随肌肉走向的构图，再定义流派、主体、线条、灰度/色彩和负空间。",
            "输出为平面白底或纸面 tattoo flash，边缘完整、可转印、远近层次清楚；不要默认生成真人皮肤照片。",
            "使用原创符号并说明必须避开的文化、宗教或帮派含义；多图时固定数量和每格职责。",
        ),
        (
            "避免细线过密、黑块粘连和缺少皮肤呼吸区。",
            "避免真实人物、现成纹身复制和未经要求的身体展示。",
        ),
        (),
        case_refs=("skill:157", "skill:158", "skill:159", "skill:160"),
        required_fields=(
            "body_placement",
            "coverage",
            "tattoo_tradition",
            "subject",
            "line_and_shading",
            "negative_space",
        ),
        hard_checks=(
            "构图适合指定身体部位和覆盖范围",
            "线条、黑灰或色彩规则统一",
            "负空间和完整轮廓支持转印",
            "输出为平面设计且不包含真人皮肤",
        ),
    ),
    PromptTemplate(
        "character-design-sheet",
        "角色设定表",
        "character",
        ("Character", "Illustration"),
        ("Story",),
        "角色设定表、动作网格、动作拆解和一致性参考",
        ("定义身份锚点、服装、比例、动作数量和版式。", "保持脸、发型和服装细节一致。"),
        ("避免动作之间服装细节变化。", "画面拥挤时减少动作数量。"),
        (347,),
        case_refs=("skill:31", "skill:32"),
    ),
    PromptTemplate(
        "3d-collectible-toy",
        "3D 收藏玩具",
        "character",
        ("3D", "Character"),
        ("Commerce", "Creative"),
        "收藏玩具、头像公仔、潮玩角色和 3D 展示图",
        ("保留参考图中的脸和服装锚点。", "指定材质、包装、底座、光线和收藏比例。"),
        ("避免缺少身份细节的通用玩具。", "包装文字保持少量且准确。"),
        (378,),
    ),
    PromptTemplate(
        "scene-storytelling",
        "场景叙事",
        "scene",
        ("Scenes", "Illustration"),
        ("Story", "Social"),
        "分镜、世界观、直播场景和情绪叙事",
        ("定义人物、地点、时间、冲突、情绪和机位。", "让场景细节服务故事。"),
        ("避免通用幻想背景。", "让故事线索在画面里可见。"),
        (330,),
        case_refs=("skill:26", "skill:29", "skill:147"),
    ),
    PromptTemplate(
        "cinematic-storyboard",
        "电影分镜板",
        "scene",
        ("Cinematic", "Animation", "Scenes"),
        ("Story", "Creative"),
        "电影、广告、动画或游戏过场的连续镜头分解与拍摄参考",
        (
            "固定镜头数量、网格和阅读顺序，为每格写叙事节拍、景别、机位、镜头运动、时长和声音/对白职责。",
            "重复角色身份、服装、道具、场景锚点、时间、光线和色板；用轴线、视线和动作方向保证剪辑连续。",
            "分镜服务拍摄和叙事，不把每格做成独立海报；标签只保留镜号和必要镜头元数据。",
        ),
        (
            "避免镜头数量错误、叙事跳跃、越轴和角色身份漂移。",
            "避免长对白、随机字幕和每格不同的艺术风格。",
        ),
        (),
        case_refs=("skill:26", "skill:28", "skill:147", "skill:152"),
        required_fields=(
            "shot_count",
            "shot_roles",
            "camera_language",
            "screen_direction",
            "identity_anchors",
            "continuity_rules",
        ),
        hard_checks=(
            "镜头数量、顺序和叙事节拍正确",
            "角色、场景、道具和光线连续",
            "轴线、视线和动作方向可剪辑",
            "每格包含必要且可读的镜头元数据",
        ),
    ),
    PromptTemplate(
        "history-classical-themes",
        "历史与古风题材",
        "history",
        ("History", "Classical", "Illustration"),
        ("History", "Story"),
        "古风题材、长卷、朝代服饰、诗词视觉和历史场景",
        ("指定朝代、服饰制度、器物参考、版式和文化气质。", "明确长卷、册页或海报形式。"),
        ("需要准确时避免朝代混搭。", "约束随机现代物件。"),
        (375, 338),
        case_refs=("skill:50", "skill:51", "skill:136"),
    ),
    PromptTemplate(
        "document-publishing",
        "文档与出版物",
        "document",
        ("Documents", "Infographic"),
        ("Education", "Tech"),
        "白皮书、手册、百科图鉴、报告页面和出版系统",
        ("定义页面尺寸、分栏、目录、图表系统和字体层级。", "使用可读标题、表格、标签和页面节奏。"),
        ("避免密集小字。", "让图表和说明对齐页面网格。"),
        (360,),
        case_refs=("skill:67", "skill:69", "skill:75"),
    ),
    PromptTemplate(
        "concept-product-breakdown",
        "概念产品研发拆解",
        "other",
        ("Other Use Cases", "Product"),
        ("Creative", "Tech"),
        "实验型任务、研发视觉板、拆解图和特殊视觉系统",
        ("定义产物类型、组件、标签、材质逻辑和展示格式。", "使用清晰标注和受控技术风格。"),
        ("避免任务边界过泛。", "标签要短且组件关系清楚。"),
        (370, 361),
        case_refs=("skill:112", "skill:113", "skill:116"),
    ),
)

STYLE_TAG_LABELS = {
    "3D": "3D",
    "Architecture": "建筑",
    "Anime": "动漫",
    "Animation": "动画",
    "Brand": "品牌",
    "Character": "角色",
    "Characters": "人物",
    "Charts": "图表",
    "Cinematic": "电影镜头",
    "Classical": "古典",
    "Concept Art": "概念设计",
    "Cyberpunk": "赛博朋克",
    "Data Visualization": "数据可视化",
    "Documents": "文档",
    "Environment": "环境",
    "Fashion Editorial": "时尚编辑",
    "Fine Art": "纯艺术",
    "Game Art": "游戏原画",
    "Game UI": "游戏界面",
    "History": "历史",
    "HUD": "HUD",
    "Icon Sheet": "图标集",
    "Illustration": "插画",
    "Infographic": "信息图",
    "Ink": "水墨",
    "Isometric": "等距视角",
    "Key Art": "关键视觉",
    "Manga": "漫画",
    "Other Use Cases": "其他",
    "Photography": "摄影",
    "Pixel Art": "像素艺术",
    "Poster": "海报",
    "Product": "商品",
    "Products": "商品",
    "Props": "道具",
    "Realistic": "写实",
    "Research Figure": "科研图",
    "Retro": "复古",
    "Scientific": "科学图解",
    "Scenes": "场景",
    "UI": "界面",
    "Tattoo": "纹身",
    "Technical Illustration": "技术插图",
    "Typography": "字体排版",
    "Watercolor": "水彩",
    "Worldbuilding": "世界观",
    "Action Board": "动作分解",
}

SCENE_TAG_LABELS = {
    "Creative": "创意",
    "Tech": "科技",
    "Commerce": "商业",
    "Education": "教育",
    "Gaming": "游戏",
    "Social": "社媒",
    "Fashion": "时尚",
    "Food": "食品饮品",
    "Travel": "旅行",
    "Story": "叙事",
    "History": "历史",
    "Healthcare": "健康医疗",
    "Lifestyle": "生活方式",
    "Events": "活动",
    "Research": "科研",
}
