from .models import PromptTemplate

# Metadata is adapted from awesome-gpt-image-2's public style library. Full case prompts stay
# in the external gallery so this application does not mirror third-party prompt content.
PROMPT_TEMPLATES = (
    PromptTemplate(
        "ui-screenshot-system",
        "UI 截图系统",
        "ui",
        ("UI",),
        ("Tech", "Social"),
        "App 截图、仪表盘、社媒截图和直播界面",
        ("锁定平台、比例、层级和画面文字。", "明确状态栏、Tab、操作区和评论层。"),
        ("避免平台描述过泛。", "约束文字可读性和平台特征。"),
        (17, 2, 4),
    ),
    PromptTemplate(
        "infographic-engine",
        "信息图引擎",
        "infographic",
        ("Infographic", "Charts"),
        ("Education", "Tech"),
        "解释图、技术图解、时间线和知识卡片",
        ("定义 3-5 个模块、信息流、层级和短标签。", "用色块、箭头、图标和留白控制复杂度。"),
        ("避免长段正文。", "先限制模块数量，再补视觉细节。"),
        (334, 1, 8),
    ),
    PromptTemplate(
        "scientific-scale-diagram",
        "科学尺度缩放图",
        "infographic",
        ("Infographic", "Charts", "Realistic"),
        ("Education", "Tech"),
        "从微观到宏观展示尺度变化的科普主题",
        ("使用 6-8 个尺度框和短标签。", "展示单位、倍率和不同尺度的细节。"),
        ("避免所有尺度框相同。", "避免通用放大镜式布局。"),
        (341,),
    ),
    PromptTemplate(
        "poster-layout-system",
        "海报排版系统",
        "poster",
        ("Poster",),
        ("Commerce", "Social"),
        "活动、电影、封面和社媒传播海报",
        ("锁定主体、标题、版式、配色和比例。", "突出标题层级和主视觉。"),
        ("避免拼贴展示板。", "约束多余文字和装饰符号。"),
        (345, 5, 10),
    ),
    PromptTemplate(
        "sports-campaign-poster",
        "运动商业 Campaign",
        "poster",
        ("Poster", "Realistic"),
        ("Commerce", "Fashion"),
        "运动品牌 Campaign、运动员和运动产品视觉",
        ("定义运动项目、姿态、核心道具、标题和品牌色。", "使用强光影、干净构图和可读数据层。"),
        ("避免错误运动器材和杂乱拼贴。", "让运动员和核心道具占据主导。"),
        (350, 3),
    ),
    PromptTemplate(
        "conceptual-typography-poster",
        "概念字体海报",
        "poster",
        ("Poster",),
        ("Creative", "Social"),
        "标题文字成为主视觉结构的海报",
        ("让字体成为画面主角并保证拼写准确。", "人物、物体或风景服务标题含义。"),
        ("避免默认字效、无关图标和标题错字。", "控制配色数量。"),
        (355,),
    ),
    PromptTemplate(
        "ink-double-exposure-poster",
        "水墨双重曝光海报",
        "poster",
        ("Poster", "Illustration", "Classical"),
        ("Story", "History"),
        "诗意人像海报、水墨氛围和文化主题视觉",
        ("融合人像剪影、水墨质感、氛围和留白。", "保持构图克制、高级、可读。"),
        ("避免廉价奇幻拼贴和景物堆叠。", "非必要时减少文字。"),
        (359,),
    ),
    PromptTemplate(
        "nature-science-poster",
        "自然科普海报",
        "poster",
        ("Poster", "Infographic"),
        ("Education",),
        "自然主题的干净科普海报",
        ("使用清晰主体、少量文案、柔和阴影和留白。", "让科普标签短而清楚。"),
        ("避免广告感过重。", "避免密集百科正文。"),
        (339,),
    ),
    PromptTemplate(
        "product-commerce-visual",
        "商品商业视觉",
        "product",
        ("Product", "Realistic"),
        ("Commerce", "Food"),
        "商品主图、包装视觉、详情页和卖点排版",
        ("定义商品、卖点、材质、场景、光线和版块。", "区分主商品、卖点标签和辅助道具。"),
        ("避免无关道具削弱商品识别。", "约束包装文字和卖点表达。"),
        (373, 358),
    ),
    PromptTemplate(
        "personalized-beauty-report",
        "个性化美妆报告",
        "product",
        ("Product", "UI"),
        ("Commerce", "Fashion"),
        "美妆推荐、肤质报告、导购助手和商品卡片",
        ("使用诊断、推荐和商品卡片的报告层级。", "对齐商品图、标签和评分。"),
        ("避免医疗化结论和难读小字。", "保持推荐逻辑清楚。"),
        (353,),
    ),
    PromptTemplate(
        "brand-identity-package",
        "品牌身份包",
        "brand",
        ("Brand",),
        ("Commerce",),
        "Logo 系统、品牌板、VI 套件和应用样机",
        ("定义品牌名、定位、配色、字体、Logo 用法和触点。", "要求视觉板中的应用统一对齐。"),
        ("避免无关 Logo 变体和混乱配色。", "保持品牌文字准确。"),
        (354,),
    ),
    PromptTemplate(
        "brand-touchpoint-board",
        "品牌触点视觉板",
        "brand",
        ("Brand", "Product"),
        ("Commerce", "Social"),
        "多触点 Campaign 展示和品牌落地预览",
        ("指定触点清单、统一视觉规则和样机排列。", "让所有面板共享配色和字体逻辑。"),
        ("避免混入无关 Campaign 风格。", "可读性下降时减少触点。"),
        (362,),
    ),
    PromptTemplate(
        "architecture-space",
        "建筑与空间",
        "architecture",
        ("Architecture",),
        ("Travel", "Commerce"),
        "室内、建筑表现、城市地图和空间规划",
        ("定义视角、尺度、材质、光线和空间功能。", "地图需指定地标、标签和相对位置。"),
        ("避免不合理透视。", "锁定地图标签语言和位置。"),
        (331, 11),
    ),
    PromptTemplate(
        "realistic-photography",
        "写实摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Fashion", "Commerce"),
        "人像、街拍、商品摄影和电影感写实",
        ("指定机位、镜头、光源、质感、背景和动作。", "加入可信的小瑕疵增强纪实感。"),
        ("商业美妆之外避免过度磨皮。", "按需约束手部、文字和结构。"),
        (377,),
    ),
    PromptTemplate(
        "street-accident-moment",
        "街头意外瞬间摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Travel", "Social"),
        "街头抓拍、意外泼洒、手机纪实和快速动作",
        ("描述具体瞬间、机位高度、运动模糊和街景。", "加入避免摆拍和棚拍感的限制。"),
        ("避免画面过于干净。", "让事件看起来可信。"),
        (376,),
    ),
    PromptTemplate(
        "illustration-art-style",
        "插画与艺术风格",
        "illustration",
        ("Illustration",),
        ("Story", "Creative"),
        "动漫、水彩、水墨、装饰画和风格实验",
        ("定义构图、主体、配色、笔触材质、情绪和完成度。", "参考图任务写明保留特征。"),
        ("避免只写风格不写构图。", "使用参考图时锁定角色识别。"),
        (346, 6),
    ),
    PromptTemplate(
        "character-design-sheet",
        "角色设定表",
        "character",
        ("Character", "Illustration"),
        ("Story",),
        "角色设定表、动作网格、动作拆解和一致性参考",
        ("定义身份锚点、服装、比例、动作数量和版式。", "保持脸、发型和服装细节一致。"),
        ("避免动作之间服装细节变化。", "画面拥挤时减少动作数量。"),
        (347,),
    ),
    PromptTemplate(
        "3d-collectible-toy",
        "3D 收藏玩具",
        "character",
        ("3D", "Character"),
        ("Commerce", "Creative"),
        "收藏玩具、头像公仔、潮玩角色和 3D 展示图",
        ("保留参考图中的脸和服装锚点。", "指定材质、包装、底座、光线和收藏比例。"),
        ("避免缺少身份细节的通用玩具。", "包装文字保持少量且准确。"),
        (378,),
    ),
    PromptTemplate(
        "scene-storytelling",
        "场景叙事",
        "scene",
        ("Scenes", "Illustration"),
        ("Story", "Social"),
        "分镜、世界观、直播场景和情绪叙事",
        ("定义人物、地点、时间、冲突、情绪和机位。", "让场景细节服务故事。"),
        ("避免通用幻想背景。", "让故事线索在画面里可见。"),
        (330,),
    ),
    PromptTemplate(
        "history-classical-themes",
        "历史与古风题材",
        "history",
        ("History", "Classical", "Illustration"),
        ("History", "Story"),
        "古风题材、长卷、朝代服饰、诗词视觉和历史场景",
        ("指定朝代、服饰制度、器物参考、版式和文化气质。", "明确长卷、册页或海报形式。"),
        ("需要准确时避免朝代混搭。", "约束随机现代物件。"),
        (375, 338),
    ),
    PromptTemplate(
        "document-publishing",
        "文档与出版物",
        "document",
        ("Documents", "Infographic"),
        ("Education", "Tech"),
        "白皮书、手册、百科图鉴、报告页面和出版系统",
        ("定义页面尺寸、分栏、目录、图表系统和字体层级。", "使用可读标题、表格、标签和页面节奏。"),
        ("避免密集小字。", "让图表和说明对齐页面网格。"),
        (360,),
    ),
    PromptTemplate(
        "concept-product-breakdown",
        "概念产品研发拆解",
        "other",
        ("Other Use Cases", "Product"),
        ("Creative", "Tech"),
        "实验型任务、研发视觉板、拆解图和特殊视觉系统",
        ("定义产物类型、组件、标签、材质逻辑和展示格式。", "使用清晰标注和受控技术风格。"),
        ("避免任务边界过泛。", "标签要短且组件关系清楚。"),
        (370, 361),
    ),
)

STYLE_TAG_LABELS = {
    "3D": "3D",
    "Architecture": "建筑",
    "Brand": "品牌",
    "Character": "角色",
    "Characters": "人物",
    "Charts": "图表",
    "Classical": "古典",
    "Documents": "文档",
    "History": "历史",
    "Illustration": "插画",
    "Infographic": "信息图",
    "Other Use Cases": "其他",
    "Photography": "摄影",
    "Poster": "海报",
    "Product": "商品",
    "Products": "商品",
    "Realistic": "写实",
    "Scenes": "场景",
    "UI": "界面",
}

SCENE_TAG_LABELS = {
    "Creative": "创意",
    "Tech": "科技",
    "Commerce": "商业",
    "Education": "教育",
    "Social": "社媒",
    "Fashion": "时尚",
    "Food": "食品饮品",
    "Travel": "旅行",
    "Story": "叙事",
    "History": "历史",
}
