from .models import PromptTemplate

# Metadata is adapted from the public awesome-gpt-image-2 and GPT-Image2-Skill galleries.
# Full case prompts stay in the external galleries so this application does not mirror them.
PROMPT_TEMPLATES = (
    PromptTemplate(
        "game-ui-gameplay-hud",
        "游戏实机 HUD",
        "game_ui",
        ("Game UI", "HUD", "UI"),
        ("Gaming", "Story"),
        "第三人称、第一人称或等距游戏的单一实机游玩 HUD",
        (
            "先写平台、目标画布、镜头语境和安全区，再按左上/右上/左下/右下/中心逐区定义 HUD；边框和装饰也必须留在安全区内。",
            "给出血量、护盾、体力、弹药、资源、任务、地图、准星等实际状态和精确数字；背景只保留能证明实机语境的可玩场景。",
            "规定 UI 层级、对齐、间距、图标尺寸、字体层级、对比度和不遮挡规则，明确这是游戏截图而不是海报。",
        ),
        (
            "避免把 HUD 元素漂浮在无逻辑的宣传构图上。",
            "避免额外 Logo、随机任务文字、乱码和越过安全区的控件。",
            "避免贴着画布边缘的全幅装饰框、角标和无功能科技线。",
        ),
        (),
        case_refs=("skill:15", "skill:18", "skill:19"),
        required_fields=(
            "platform",
            "canvas",
            "screen_type",
            "hud_zones",
            "safe_area",
            "exact_text",
            "ui_states",
        ),
        hard_checks=(
            "输出为单一实机游玩状态而非海报",
            "HUD 分区完整且不遮挡主要可玩信息",
            "关键数值和文字逐字可读",
            "没有越过安全区的全幅装饰边框",
        ),
    ),
    PromptTemplate(
        "game-ui-menu-inventory",
        "游戏菜单 / 背包界面",
        "game_ui",
        ("Game UI", "UI", "Infographic"),
        ("Gaming", "Tech"),
        "暂停菜单、角色状态、背包、装备或技能页面的单一界面状态",
        (
            "明确屏幕用途、导航层级、选中项、分页、物品格数量和信息密度；给出一个可执行的静态状态。",
            "把角色预览、物品缩略图、属性数值、稀有度、容量和操作提示分成固定区域，统一卡片、图标和网格间距。",
            "所有标题、属性和按钮文案使用短的原创游戏术语；优先高对比和可扫描性，不用装饰性长文案。",
        ),
        (
            "避免同时展示背包、地图、商店和战斗 HUD 多个页面。",
            "避免卡片数量、选中状态和操作提示互相矛盾。",
        ),
        (),
        case_refs=("skill:17", "skill:20"),
        required_fields=(
            "platform",
            "screen_type",
            "navigation",
            "selected_state",
            "grid_and_slots",
            "exact_text",
        ),
        hard_checks=(
            "页面类型和选中状态明确",
            "物品格与属性区域数量一致",
            "导航、标题和操作提示可读",
        ),
    ),
    PromptTemplate(
        "game-ui-map-quest",
        "游戏地图 / 任务界面",
        "game_ui",
        ("Game UI", "HUD", "Infographic"),
        ("Gaming", "Tech"),
        "世界地图、区域地图、任务日志、指南针和路线规划界面",
        (
            "先确定地图尺度、朝向、玩家位置、任务目标、路线、图例和缩放层级，固定每类标记的视觉编码。",
            "把地图内容、任务面板、指南针/坐标和操作提示分区，标签只用确认过的短词，保证地标与标记的相对位置清楚。",
            "地图要有游戏世界的可玩信息和空间关系，不做旅游海报；使用原创地点名和图例。",
        ),
        (
            "避免随机地名、重叠标记、没有方向的地图和过密长文本。",
            "避免把任务日志与战斗 HUD 叠成无层级的界面。",
        ),
        (),
        case_refs=("skill:19", "skill:21"),
        required_fields=(
            "platform",
            "screen_type",
            "map_scale",
            "orientation",
            "markers_and_legend",
            "quest_text",
        ),
        hard_checks=(
            "玩家、目标和路线关系清楚",
            "图例与标记编码一致",
            "任务文字短且可读",
        ),
    ),
    PromptTemplate(
        "game-ui-icon-sheet",
        "游戏图标资产集",
        "game_ui",
        ("Game UI", "Icon Sheet", "Illustration"),
        ("Gaming", "Creative"),
        "技能、装备、物品、状态效果和地图标记的统一图标集",
        (
            "固定网格行列、图标总数、每格职责、显示尺寸、背景和透明/纯色输出规则；每个图标只表达一个可读语义。",
            "统一轮廓、视角、描边/材质、光源、稀有度色板和留白；用编号或极短标签对应图标职责。",
            "图标要在实际 HUD 尺寸下仍能辨认，禁止把图标集做成角色海报或无用途的装饰拼贴。",
        ),
        (
            "避免图标数量不符、语义重复、视角和材质混乱。",
            "避免随机字母、品牌 Logo、复杂背景和无法缩小的细节。",
        ),
        (),
        case_refs=("skill:20", "awesome:370"),
        required_fields=(
            "platform",
            "grid",
            "icon_count",
            "icon_roles",
            "display_size",
            "palette",
        ),
        hard_checks=(
            "网格和图标数量正确",
            "每个图标语义独立且风格统一",
            "缩小后轮廓仍清晰",
        ),
    ),
    PromptTemplate(
        "game-art-key-visual",
        "游戏 Key Art / 主视觉",
        "game_art",
        ("Game Art", "Key Art", "Concept Art"),
        ("Gaming", "Story"),
        "游戏宣传主视觉、章节封面或核心事件的单张 Key Art",
        (
            "明确游戏世界、阵营、角色身份、正在发生的事件和交付用途；只保留一个主叙事瞬间和一个视觉中心。",
            "写清前景/中景/背景、镜头高度、焦段感、动作方向、尺度参照、材质和光线，让画面服务可玩世界。",
            "原创标题或短标签若非必要就不加入；禁止真实游戏 Logo/IP，保留可供美术继续开发的轮廓和色板信息。",
        ),
        (
            "避免把 Key Art 变成角色表、九宫格或 UI 截图。",
            "避免堆叠多个高潮动作、无尺度的背景和无关文字。",
        ),
        (),
        case_refs=("awesome:473", "awesome:395", "awesome:394"),
        required_fields=(
            "deliverable_stage",
            "world_and_faction",
            "identity_anchors",
            "camera_and_action",
            "composition",
            "palette_and_lighting",
        ),
        hard_checks=(
            "只有一个明确叙事瞬间和视觉中心",
            "角色身份与世界尺度可信",
            "无真实 IP、Logo 和额外文字",
        ),
    ),
    PromptTemplate(
        "game-art-character-sheet",
        "游戏角色设定表",
        "game_art",
        ("Game Art", "Character", "Concept Art"),
        ("Gaming", "Story"),
        "角色三视图、表情、服装装备和比例参考设定表",
        (
            "固定页面网格和视图职责：正面/侧面/背面、动作或表情、服装层级、装备拆解和色板。",
            "先锁身份锚点（脸型、发型、体型、服装剪影、阵营符号和主色），所有面板复用同一角色和同一装备状态。",
            "白发、疤痕、单侧护甲和机械臂等非对称锚点必须写明角色左右，并映射到正面、侧面、背面和头像中的观看方向。",
            "标注只写短的部件名或材质名；让比例、关节、鞋底、武器握持和功能细节可供制作参考。",
        ),
        (
            "避免面板间换脸、换发型、换装备、比例漂移或随机角色。",
            "避免把角色设定表做成只有一张大头像的海报。",
        ),
        (),
        case_refs=("skill:31", "skill:32", "awesome:439"),
        required_fields=(
            "panel_count",
            "panel_roles",
            "identity_anchors",
            "directional_identity_map",
            "views_and_expressions",
            "costume_and_equipment",
            "palette",
        ),
        hard_checks=(
            "视图和面板数量正确",
            "所有面板保持同一身份、服装、装备及非对称特征方向",
            "部件标签短且可读",
        ),
    ),
    PromptTemplate(
        "game-art-environment",
        "游戏环境概念图",
        "game_art",
        ("Game Art", "Environment", "Concept Art"),
        ("Gaming", "Story"),
        "关卡环境、城镇、遗迹、战场和可探索空间的环境概念",
        (
            "说明关卡功能、玩家动线、关键地标、入口/出口、可交互物和尺度参照，而不是只写‘宏大风景’。",
            "明确镜头高度、视线引导、前中后景、材质分层、天气和主光方向；关键区域要能支持导航与玩法。",
            "保留适度的制作信息（模块化结构、重复材质、破损逻辑和色板），让环境概念能转成关卡语言。",
        ),
        (
            "避免没有玩法线索的壁纸式风景。",
            "避免建筑结构、尺度、光源和动线互相矛盾。",
        ),
        (),
        case_refs=("awesome:473", "awesome:448", "awesome:394"),
        required_fields=(
            "environment_function",
            "player_route",
            "landmarks",
            "scale_reference",
            "camera",
            "materials",
            "lighting",
        ),
        hard_checks=(
            "关键地标和玩家动线可读",
            "尺度、结构和光线一致",
            "环境细节服务玩法而非纯装饰",
        ),
    ),
    PromptTemplate(
        "game-art-prop-weapon",
        "游戏武器 / 道具设计",
        "game_art",
        ("Game Art", "Props", "Concept Art"),
        ("Gaming", "Tech"),
        "武器、装备、载具部件和关键道具的制作设计页",
        (
            "先写功能、使用者、尺寸级别和关键轮廓，再安排正交视图、握持/使用状态、材质拆分和局部放大。",
            "用结构、连接、磨损、能源/机械逻辑和尺度参照证明它能在游戏世界里工作；需要时加入简短部件标签。",
            "固定面板数量和职责，统一视角、光线、色板与原创阵营符号，避免只画一个漂亮但不可制作的物件。",
        ),
        (
            "避免功能、比例、连接关系和视图相互矛盾。",
            "避免随机技术文字、真实品牌和无关武器堆叠。",
        ),
        (),
        case_refs=("skill:112", "skill:113", "skill:114", "awesome:370"),
        required_fields=(
            "prop_function",
            "user_and_scale",
            "views",
            "material_breakdown",
            "mechanical_details",
            "callouts",
        ),
        hard_checks=(
            "视图和部件关系一致",
            "尺度、功能和材质可判断",
            "标签只包含必要短文本",
        ),
    ),
    PromptTemplate(
        "game-art-worldbuilding-board",
        "游戏世界观设定板",
        "game_art",
        ("Game Art", "Worldbuilding", "Concept Art"),
        ("Gaming", "Creative"),
        "3×3 或指定网格的阵营、地点、角色、道具和事件世界观板",
        (
            "先锁定网格数量和每格职责；所有格子共享游戏名、时代、阵营、色板、材质、符号和光线规则。",
            "为每格指定一个互补的制作问题（角色、敌人、环境、道具、事件、地图等），而不是生成九张相互无关的插图。",
            "页眉、短标题和标注只服务检索；确保跨面板身份、服装、装备和世界规则一致。",
        ),
        (
            "避免面板数量漂移、重复内容、无关风格和随机长文案。",
            "避免把外部游戏案例中的角色、Logo 或名称直接带入原创项目。",
        ),
        (),
        case_refs=("skill:22", "awesome:473"),
        required_fields=(
            "panel_count",
            "panel_roles",
            "shared_identity_anchors",
            "shared_palette",
            "shared_materials",
            "labels",
        ),
        hard_checks=(
            "网格数量和每格职责正确",
            "所有面板共享同一世界规则",
            "无额外面板、IP 和无关文字",
        ),
    ),
    PromptTemplate(
        "game-art-action-breakdown",
        "游戏动作分解板",
        "game_art",
        ("Game Art", "Action Board", "Character"),
        ("Gaming", "Story"),
        "攻击、移动、受击、施法和交互动作的连续分解参考板",
        (
            "固定帧数或网格、阅读顺序和每帧职责；同一角色、服装、武器、镜头轴线和背景锚点贯穿全部帧。",
            "写清起势、发力、接触、峰值、回收和残影/特效的动作节拍，用轮廓、重心、运动线和接触点服务动画制作。",
            "必要标签保持短且准确，避免把动作分解变成多张独立海报或不同角色的姿势合集。",
        ),
        (
            "避免帧数不一致、动作顺序混乱、角色身份漂移和镜头轴线跳变。",
            "避免无关装饰、长段说明和真实游戏动作复刻。",
        ),
        (),
        case_refs=("awesome:347", "skill:32"),
        required_fields=(
            "frame_count",
            "frame_roles",
            "identity_anchors",
            "action_beats",
            "camera_axis",
            "effects",
        ),
        hard_checks=(
            "帧数、顺序和动作节拍正确",
            "角色、服装、武器和镜头轴线一致",
            "每帧都能判断动作阶段",
        ),
    ),
    PromptTemplate(
        "ui-screenshot-system",
        "UI 截图系统",
        "ui",
        ("UI",),
        ("Tech", "Social"),
        "App 截图、仪表盘、社媒截图和直播界面",
        ("锁定平台、比例、层级和画面文字。", "明确状态栏、Tab、操作区和评论层。"),
        ("避免平台描述过泛。", "约束文字可读性和平台特征。"),
        (17, 2, 4),
    ),
    PromptTemplate(
        "infographic-engine",
        "信息图引擎",
        "infographic",
        ("Infographic", "Charts"),
        ("Education", "Tech"),
        "解释图、技术图解、时间线和知识卡片",
        ("定义 3-5 个模块、信息流、层级和短标签。", "用色块、箭头、图标和留白控制复杂度。"),
        ("避免长段正文。", "先限制模块数量，再补视觉细节。"),
        (334, 1, 8),
    ),
    PromptTemplate(
        "scientific-scale-diagram",
        "科学尺度缩放图",
        "infographic",
        ("Infographic", "Charts", "Realistic"),
        ("Education", "Tech"),
        "从微观到宏观展示尺度变化的科普主题",
        ("使用 6-8 个尺度框和短标签。", "展示单位、倍率和不同尺度的细节。"),
        ("避免所有尺度框相同。", "避免通用放大镜式布局。"),
        (341,),
    ),
    PromptTemplate(
        "poster-layout-system",
        "海报排版系统",
        "poster",
        ("Poster",),
        ("Commerce", "Social"),
        "活动、电影、封面和社媒传播海报",
        ("锁定主体、标题、版式、配色和比例。", "突出标题层级和主视觉。"),
        ("避免拼贴展示板。", "约束多余文字和装饰符号。"),
        (345, 5, 10),
    ),
    PromptTemplate(
        "sports-campaign-poster",
        "运动商业 Campaign",
        "poster",
        ("Poster", "Realistic"),
        ("Commerce", "Fashion"),
        "运动品牌 Campaign、运动员和运动产品视觉",
        ("定义运动项目、姿态、核心道具、标题和品牌色。", "使用强光影、干净构图和可读数据层。"),
        ("避免错误运动器材和杂乱拼贴。", "让运动员和核心道具占据主导。"),
        (350, 3),
    ),
    PromptTemplate(
        "conceptual-typography-poster",
        "概念字体海报",
        "poster",
        ("Poster",),
        ("Creative", "Social"),
        "标题文字成为主视觉结构的海报",
        ("让字体成为画面主角并保证拼写准确。", "人物、物体或风景服务标题含义。"),
        ("避免默认字效、无关图标和标题错字。", "控制配色数量。"),
        (355,),
    ),
    PromptTemplate(
        "ink-double-exposure-poster",
        "水墨双重曝光海报",
        "poster",
        ("Poster", "Illustration", "Classical"),
        ("Story", "History"),
        "诗意人像海报、水墨氛围和文化主题视觉",
        ("融合人像剪影、水墨质感、氛围和留白。", "保持构图克制、高级、可读。"),
        ("避免廉价奇幻拼贴和景物堆叠。", "非必要时减少文字。"),
        (359,),
    ),
    PromptTemplate(
        "nature-science-poster",
        "自然科普海报",
        "poster",
        ("Poster", "Infographic"),
        ("Education",),
        "自然主题的干净科普海报",
        ("使用清晰主体、少量文案、柔和阴影和留白。", "让科普标签短而清楚。"),
        ("避免广告感过重。", "避免密集百科正文。"),
        (339,),
    ),
    PromptTemplate(
        "product-commerce-visual",
        "商品商业视觉",
        "product",
        ("Product", "Realistic"),
        ("Commerce", "Food"),
        "商品主图、包装视觉、详情页和卖点排版",
        ("定义商品、卖点、材质、场景、光线和版块。", "区分主商品、卖点标签和辅助道具。"),
        ("避免无关道具削弱商品识别。", "约束包装文字和卖点表达。"),
        (373, 358),
    ),
    PromptTemplate(
        "personalized-beauty-report",
        "个性化美妆报告",
        "product",
        ("Product", "UI"),
        ("Commerce", "Fashion"),
        "美妆推荐、肤质报告、导购助手和商品卡片",
        ("使用诊断、推荐和商品卡片的报告层级。", "对齐商品图、标签和评分。"),
        ("避免医疗化结论和难读小字。", "保持推荐逻辑清楚。"),
        (353,),
    ),
    PromptTemplate(
        "brand-identity-package",
        "品牌身份包",
        "brand",
        ("Brand",),
        ("Commerce",),
        "Logo 系统、品牌板、VI 套件和应用样机",
        ("定义品牌名、定位、配色、字体、Logo 用法和触点。", "要求视觉板中的应用统一对齐。"),
        ("避免无关 Logo 变体和混乱配色。", "保持品牌文字准确。"),
        (354,),
    ),
    PromptTemplate(
        "brand-touchpoint-board",
        "品牌触点视觉板",
        "brand",
        ("Brand", "Product"),
        ("Commerce", "Social"),
        "多触点 Campaign 展示和品牌落地预览",
        ("指定触点清单、统一视觉规则和样机排列。", "让所有面板共享配色和字体逻辑。"),
        ("避免混入无关 Campaign 风格。", "可读性下降时减少触点。"),
        (362,),
    ),
    PromptTemplate(
        "architecture-space",
        "建筑与空间",
        "architecture",
        ("Architecture",),
        ("Travel", "Commerce"),
        "室内、建筑表现、城市地图和空间规划",
        ("定义视角、尺度、材质、光线和空间功能。", "地图需指定地标、标签和相对位置。"),
        ("避免不合理透视。", "锁定地图标签语言和位置。"),
        (331, 11),
    ),
    PromptTemplate(
        "realistic-photography",
        "写实摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Fashion", "Commerce"),
        "人像、街拍、商品摄影和电影感写实",
        ("指定机位、镜头、光源、质感、背景和动作。", "加入可信的小瑕疵增强纪实感。"),
        ("商业美妆之外避免过度磨皮。", "按需约束手部、文字和结构。"),
        (377,),
    ),
    PromptTemplate(
        "street-accident-moment",
        "街头意外瞬间摄影",
        "photo",
        ("Photography", "Realistic"),
        ("Travel", "Social"),
        "街头抓拍、意外泼洒、手机纪实和快速动作",
        ("描述具体瞬间、机位高度、运动模糊和街景。", "加入避免摆拍和棚拍感的限制。"),
        ("避免画面过于干净。", "让事件看起来可信。"),
        (376,),
    ),
    PromptTemplate(
        "illustration-art-style",
        "插画与艺术风格",
        "illustration",
        ("Illustration",),
        ("Story", "Creative"),
        "动漫、水彩、水墨、装饰画和风格实验",
        ("定义构图、主体、配色、笔触材质、情绪和完成度。", "参考图任务写明保留特征。"),
        ("避免只写风格不写构图。", "使用参考图时锁定角色识别。"),
        (346, 6),
    ),
    PromptTemplate(
        "character-design-sheet",
        "角色设定表",
        "character",
        ("Character", "Illustration"),
        ("Story",),
        "角色设定表、动作网格、动作拆解和一致性参考",
        ("定义身份锚点、服装、比例、动作数量和版式。", "保持脸、发型和服装细节一致。"),
        ("避免动作之间服装细节变化。", "画面拥挤时减少动作数量。"),
        (347,),
    ),
    PromptTemplate(
        "3d-collectible-toy",
        "3D 收藏玩具",
        "character",
        ("3D", "Character"),
        ("Commerce", "Creative"),
        "收藏玩具、头像公仔、潮玩角色和 3D 展示图",
        ("保留参考图中的脸和服装锚点。", "指定材质、包装、底座、光线和收藏比例。"),
        ("避免缺少身份细节的通用玩具。", "包装文字保持少量且准确。"),
        (378,),
    ),
    PromptTemplate(
        "scene-storytelling",
        "场景叙事",
        "scene",
        ("Scenes", "Illustration"),
        ("Story", "Social"),
        "分镜、世界观、直播场景和情绪叙事",
        ("定义人物、地点、时间、冲突、情绪和机位。", "让场景细节服务故事。"),
        ("避免通用幻想背景。", "让故事线索在画面里可见。"),
        (330,),
    ),
    PromptTemplate(
        "history-classical-themes",
        "历史与古风题材",
        "history",
        ("History", "Classical", "Illustration"),
        ("History", "Story"),
        "古风题材、长卷、朝代服饰、诗词视觉和历史场景",
        ("指定朝代、服饰制度、器物参考、版式和文化气质。", "明确长卷、册页或海报形式。"),
        ("需要准确时避免朝代混搭。", "约束随机现代物件。"),
        (375, 338),
    ),
    PromptTemplate(
        "document-publishing",
        "文档与出版物",
        "document",
        ("Documents", "Infographic"),
        ("Education", "Tech"),
        "白皮书、手册、百科图鉴、报告页面和出版系统",
        ("定义页面尺寸、分栏、目录、图表系统和字体层级。", "使用可读标题、表格、标签和页面节奏。"),
        ("避免密集小字。", "让图表和说明对齐页面网格。"),
        (360,),
    ),
    PromptTemplate(
        "concept-product-breakdown",
        "概念产品研发拆解",
        "other",
        ("Other Use Cases", "Product"),
        ("Creative", "Tech"),
        "实验型任务、研发视觉板、拆解图和特殊视觉系统",
        ("定义产物类型、组件、标签、材质逻辑和展示格式。", "使用清晰标注和受控技术风格。"),
        ("避免任务边界过泛。", "标签要短且组件关系清楚。"),
        (370, 361),
    ),
)

STYLE_TAG_LABELS = {
    "3D": "3D",
    "Architecture": "建筑",
    "Brand": "品牌",
    "Character": "角色",
    "Characters": "人物",
    "Charts": "图表",
    "Classical": "古典",
    "Concept Art": "概念设计",
    "Documents": "文档",
    "Environment": "环境",
    "Game Art": "游戏原画",
    "Game UI": "游戏界面",
    "History": "历史",
    "HUD": "HUD",
    "Icon Sheet": "图标集",
    "Illustration": "插画",
    "Infographic": "信息图",
    "Key Art": "关键视觉",
    "Other Use Cases": "其他",
    "Photography": "摄影",
    "Poster": "海报",
    "Product": "商品",
    "Products": "商品",
    "Props": "道具",
    "Realistic": "写实",
    "Scenes": "场景",
    "UI": "界面",
    "Worldbuilding": "世界观",
    "Action Board": "动作分解",
}

SCENE_TAG_LABELS = {
    "Creative": "创意",
    "Tech": "科技",
    "Commerce": "商业",
    "Education": "教育",
    "Gaming": "游戏",
    "Social": "社媒",
    "Fashion": "时尚",
    "Food": "食品饮品",
    "Travel": "旅行",
    "Story": "叙事",
    "History": "历史",
}
