"""initial schema

Revision ID: 5728b5736599
Revises:
Create Date: 2026-07-14 11:48:44.297849
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5728b5736599"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_state",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("balance_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reserved_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("generation_concurrency", sa.Integer(), nullable=False),
        sa.Column("password_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("balance_rmb >= 0", name="ck_users_balance_non_negative"),
        sa.CheckConstraint("generation_concurrency BETWEEN 1 AND 16", name="ck_users_concurrency"),
        sa.CheckConstraint("reserved_rmb >= 0", name="ck_users_reserved_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index("ix_audit_logs_created", ["created_at"], unique=False)

    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_workspaces_user_name"),
    )
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspaces_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_workspaces_user_updated", ["user_id", "updated_at"], unique=False)

    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_path"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_sha256"), ["sha256"], unique=False)
        batch_op.create_index(
            "ix_assets_workspace_active", ["workspace_id", "deleted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_assets_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("provider_label", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=150), nullable=False),
        sa.Column("upstream_request_id", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("elapsed_seconds", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_messages_kind"), ["kind"], unique=False)
        batch_op.create_index(
            "ix_conversation_messages_workspace_created",
            ["workspace_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_workspace_id"),
            ["workspace_id"],
            unique=False,
        )

    op.create_table(
        "conversation_state",
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("summary_through_message_id", sa.String(length=32), nullable=False),
        sa.Column("estimated_context_tokens", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("channel_label", sa.String(length=100), nullable=False),
        sa.Column("channel_config_version", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("size", sa.String(length=20), nullable=False),
        sa.Column("quality", sa.String(length=20), nullable=False),
        sa.Column("output_format", sa.String(length=20), nullable=False),
        sa.Column("compression", sa.Integer(), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("price_per_image_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reserved_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("charged_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generation_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_jobs_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_generation_jobs_user_status", ["user_id", "status"], unique=False)
        batch_op.create_index(
            "ix_generation_jobs_workspace_created",
            ["workspace_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_workspace_id"),
            ["workspace_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_generation_jobs_workspace_active",
            ["workspace_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('queued', 'running', 'canceling')"),
            postgresql_where=sa.text("status IN ('queued', 'running', 'canceling')"),
        )

    op.create_table(
        "conversation_attachments",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["message_id"], ["conversation_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "asset_id"),
        sa.UniqueConstraint("message_id", "position", name="uq_conversation_attachment_position"),
    )
    op.create_table(
        "generation_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("estimated_seconds", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("upstream_status", sa.Integer(), nullable=True),
        sa.Column("upstream_request_id", sa.String(length=255), nullable=True),
        sa.Column("elapsed_seconds", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("charged_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("output_mime_type", sa.String(length=50), nullable=True),
        sa.Column("output_byte_count", sa.Integer(), nullable=True),
        sa.Column("output_width", sa.Integer(), nullable=True),
        sa.Column("output_height", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "position", name="uq_generation_item_position"),
        sa.UniqueConstraint("output_path"),
        sa.UniqueConstraint("thumbnail_path"),
    )
    with op.batch_alter_table("generation_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generation_items_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(
            "ix_generation_items_channel_status", ["channel_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generation_items_job_id"), ["job_id"], unique=False)
        batch_op.create_index("ix_generation_items_queue", ["status", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_items_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_items_user_id"), ["user_id"], unique=False)

    op.create_table(
        "generation_references",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "asset_id"),
        sa.UniqueConstraint("job_id", "position", name="uq_job_reference_position"),
    )
    op.create_table(
        "wallet_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("generation_item_id", sa.String(length=32), nullable=True),
        sa.Column("entry_type", sa.String(length=40), nullable=False),
        sa.Column("amount_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("balance_after_rmb", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["generation_item_id"], ["generation_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_item_id", name="uq_wallet_generation_item"),
    )
    with op.batch_alter_table("wallet_ledger", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wallet_ledger_actor_user_id"),
            ["actor_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wallet_ledger_entry_type"), ["entry_type"], unique=False
        )
        batch_op.create_index(
            "ix_wallet_ledger_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_wallet_ledger_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wallet_ledger_user_id"))
        batch_op.drop_index("ix_wallet_ledger_user_created")
        batch_op.drop_index(batch_op.f("ix_wallet_ledger_entry_type"))
        batch_op.drop_index(batch_op.f("ix_wallet_ledger_actor_user_id"))

    op.drop_table("wallet_ledger")
    op.drop_table("generation_references")
    with op.batch_alter_table("generation_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_items_user_id"))
        batch_op.drop_index(batch_op.f("ix_generation_items_status"))
        batch_op.drop_index("ix_generation_items_queue")
        batch_op.drop_index(batch_op.f("ix_generation_items_job_id"))
        batch_op.drop_index("ix_generation_items_channel_status")
        batch_op.drop_index(batch_op.f("ix_generation_items_channel_id"))

    op.drop_table("generation_items")
    op.drop_table("conversation_attachments")
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_generation_jobs_workspace_active",
            sqlite_where=sa.text("status IN ('queued', 'running', 'canceling')"),
            postgresql_where=sa.text("status IN ('queued', 'running', 'canceling')"),
        )
        batch_op.drop_index(batch_op.f("ix_generation_jobs_workspace_id"))
        batch_op.drop_index("ix_generation_jobs_workspace_created")
        batch_op.drop_index("ix_generation_jobs_user_status")
        batch_op.drop_index(batch_op.f("ix_generation_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_channel_id"))

    op.drop_table("generation_jobs")
    op.drop_table("conversation_state")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_workspace_id"))
        batch_op.drop_index("ix_conversation_messages_workspace_created")
        batch_op.drop_index(batch_op.f("ix_conversation_messages_kind"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_workspace_id"))
        batch_op.drop_index("ix_assets_workspace_active")
        batch_op.drop_index(batch_op.f("ix_assets_sha256"))

    op.drop_table("assets")
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_index("ix_workspaces_user_updated")
        batch_op.drop_index(batch_op.f("ix_workspaces_user_id"))

    op.drop_table("workspaces")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_created")
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_status"))
        batch_op.drop_index(batch_op.f("ix_users_role"))

    op.drop_table("users")
    op.drop_table("system_state")
    # ### end Alembic commands ###
